version: 2.1
orbs:
  nx: nrwl/nx@1.4.0
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm install -g pnpm
      - run: pnpm install
      - nx/set-shas

      - run: npx nx workspace-lint
      - run: npx nx format:check --libs-and-apps
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
workflows:
  build:
    jobs:
      - main
