name: 'CD: Commit'
on:
  push:
    branches: [release]

defaults:
  run:
    shell: bash

jobs:
  install_deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.11

      - name: Print node/pnpm versions
        id: versions
        run: |
          node_ver=$( node --version )
          pnpm_ver=$( pnpm --version )
          echo "Node: ${node_ver:1}"
          echo "PNPM: ${pnpm_ver:1}"
          echo "::set-output name=node_version::${node_ver:1}"

      - name: Restore "node_modules" from cache
        id: cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-
          restore-keys: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: node_modules
          key: ${{ steps.cache.outputs.primary-key }}

  lint:
    runs-on: self-hosted
    needs: install_deps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Print node/npm/yarn versions
        id: versions
        run: |
          node_ver=$( node --version )
          pnpm_ver=$( pnpm --version || true )
          echo "Node: ${node_ver:1}"
          echo "PNPM: ${pnpm_ver:1}"
          if [[ $pnpm_ver != '' ]]; then echo "PNPM: $pnpm_ver"; fi
          echo "::set-output name=node_version::${node_ver:1}"

      - name: Restore "node_modules" from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      - run: npx nx affected --target=lint --parallel=1 --base=$NX_BASE --head=$NX_HEAD

  test:
    needs: install_deps
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1

      - name: Print node/npm/yarn versions
        id: versions
        run: |
          node_ver=$( node --version )
          pnpm_ver=$( pnpm --version || true )
          echo "Node: ${node_ver:1}"
          echo "PNPM: ${pnpm_ver:1}"
          if [[ $pnpm_ver != '' ]]; then echo "PNPM: $pnpm_ver"; fi
          echo "::set-output name=node_version::${node_ver:1}"

      - name: Restore "node_modules" from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      - run: npx nx affected --target=test --parallel=1 --base=$NX_BASE --head=$NX_HEAD
