name: 'CI: Pull Request'

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  install_deps:
    name: Installing Dependencies
    uses: VT-Codes/actions/.github/workflows/install.yml@main

  lint:
    needs: install_deps
    name: Linting files...
    uses: VT-Codes/actions/.github/workflows/lint.yml@main

  test:
    name: Testing files...
    needs: install_deps
    uses: VT-Codes/actions/.github/workflows/test.yml@main
